# CONFIGURATION FILE 
# All paths are to be given without final slash.

# Path 
pathFlow: '/Users/joaoisler/Library/CloudStorage/GoogleDrive-joao.isler@gmail.com/My Drive/bsc/scramjet/afrl/2d/cases/euler/case'
pathMesh: '/Users/joaoisler/Library/CloudStorage/GoogleDrive-joao.isler@gmail.com/My Drive/bsc/scramjet/afrl/2d/meshes/mesh2'
pathRes: '/Users/joaoisler/Library/CloudStorage/GoogleDrive-joao.isler@gmail.com/My Drive/bsc/pinns/PINNs/results' 
pathData: '/Users/joaoisler/Library/CloudStorage/GoogleDrive-joao.isler@gmail.com/My Drive/bsc/pinns/PINNs/data' 
 
# Flow field file
flowfield: 'flow.vtu' 
mesh: 'afrl2d.geo'

# Routines
routine:
  plotflow: True
  sampling: True
  inference: True
  identification: False

plotflow:
  fields: ["Density", "Pressure", "Velocity", "Velocity"]
  latex: ['$\rho$ $[kg/m^{3}]$', '$p$ $[Pa]$', '$u$ $[m/s]$', '$v$ $[m/s]$']
  comp: [0, 0, 0, 1]
  cmap: ['bwr', 'bwr', 'bwr', 'bwr']
  scale: [[0,1.3],[1.3e4,1.67e5],[-750, 950],[-315,315]]

# Sampling parameters
sampling:
  nspoin: 2100
  nspoin_grad: 2300 # grad
  type: 'lhs' # random, lhs
  grad_type_var: 'Density'
  bc: ['inlet','bottom','outlet','top']
  nspoin_bc: [40, 260, 40, 160]
  pool_factor: 8
  alpha_grad_rho: 1.4
  seed: 1234
  fpoints: 'all_points'
  ftargets: 'target_points'
  fdata: 'sampling_data'


# PINNs steup
N_train: 600
N_AdamIter: 50000
layers: [2, 64, 64, 64, 64, 4]

# General parameters
dims: 2

# Heat capacity ratio 
gamma: 1.4
# Reference quatities
H: 0.0508
Lref: 0.0254 # m
# Freestream condition
U_0: 727.0 # m/s
T: 327.0   # K
p: 61700   # Pa
rho: 0.657 # kg/m^3
# Turbulence modeling
k: 7884.91         # m^2/s^2
omega: 2.62957e+07 # 1/s