# CONFIGURATION FILE 
# All paths are to be given without final slash.

# Paths
# -----
paths:
  flow: ""
  mesh: ""
  results: ""
  data: ""
  model: ""

# Name
# ----
  name: afrl_scramjet

# Geometry
# --------
geometry:
  dimension: 2

# Random number generation
# ------------------------
seed: 1234

# Files
# -----
files:
  flowfield: "flow.vtu"
  mesh: "afrl2d.geo"
  model_name: "pinn_mlp_model"

# Run setup
# ---------
run:
  model: "pinn"          # Options: supervised or pinn
  equation: "Euler"      # Options: Euler or RANS
  device: "cuda"         # Options: cpu or cuda

  routines:
    sampling: true
    inference: true
    identification: false
    postprocessing: true

  checkpoint:
    load_model: false
    save_model: false

  verbose: true

# Neural network
# --------------
network:
  architecture: "mlp"       # Options: mlp or gnn 

  mlp:
    layers: [2, 32, 32, 32, 4] 
    activation: "tanh" # Options: tanh, sigmoid, sin, softplus, silu/swish, gelu

    dropout:
      probability: 0.0
      hidden_layer_indices: [1, 2]

  gnn:
    latent_dim: 8
    activation: "tanh" # Options: tanh, sigmoid, sin, softplus, silu/swish, gelu
    neighbors: 6             # Used when construction

    attributes:
      node:
        boundary_marker: false # TODO 
        
      edge:
        distance: true                

    processor:
      message_layers: 4  
      aggregation: "sum" # Options: sum, max, mean
      residual: true

# Sampling
# --------
sampling:
  method: "lhs"       # random or lhs

  boundaries:
    names:
      - "inlet"
      - "bottom"
      - "outlet"
      - "top"

  data_points:
    interior: 2100
    gradient: 2300
    boundary: [40, 260, 40, 160]

  collocation_points:
    interior: 2100
    gradient: 2300
    boundary: [40, 260, 40, 160]

  gradient_sampling:
    variable: "Density"
    pool_factor: 8
    alpha: 1.4

  plot_files:
    data: "pl_data"
    collocation: "pl_coll"
    all: "pl_all"
    training: "pl_training"

  data_files:
    data: "data_points"
    collocation: "collocation_points"

# Dataset split
# -------------
dataset:
  n_train_data: 3500
  n_train_collocation: 3500
  n_validation_data: 750
  n_test_data: 750

# Optimizers
# ----------
optimizer:
  adam:
    enabled: true
    iterations: 20
    learning_rate: 4.0e-4

    scheduler:
      step_size: 2000
      gamma: 0.8

  # starts after adam optimizer finishes
  # if both are enabled.
  lbfgs:
    enabled: true
    iterations: 20
    learning_rate: 1.0
    max_iter_per_step: 30

# Loss
# ----
loss:
  print_frequency: 10

  weights:
    data:
      rho: 1.0
      u: 1.0
      v: 200.0
      p: 4.0
      mut: 1.0

    residual:
      f1: 1.0
      f2: 1.0
      f3: 1.0
      f4: 1.0

# Physical parameters
# -------------------
physics:
  gas:
    gamma: 1.4        # Heat capacity ratio
    R: 287.058        # J/(kg K) - Universal gas constant

  reference:
    Lref: 0.0254      # m
    U_0: 727.0        # m/s
    rho: 0.657        # kg/m^3
    mu: 1.97e-5       # N s / m^2 - Dynamic viscosity - freestream

  turbulence:
    Pr: 0.72          # Laminar Prandtl number
    Prt: 0.9          # Turbulent Prandtl number

  sutherland:
    T0: 273.15        # K
    mu0: 1.716e-5     # N s / m^2
    S: 110.4          # K

# Post processing 
# ---------------
post_processing:
  error_type: abs_error_01 # Options: error, abs_error, rel_error, abs_error_01

  fields: # from CFD
    - "Density"
    - "Pressure"
    - "Velocity"
    - "Velocity"
    #- "Eddy_Viscosity"

  latex:
    - "$\\rho$ $[kg/m^{3}]$"
    - "$p$ $[Pa]$"
    - "$u$ $[m/s]$"
    - "$v$ $[m/s]$"
    #- "$\\hat{\\mu}_{t}$ $[kg/m \\cdot s]$"  
    
  components: [0, 0, 0, 1] #, 0

  colormaps:
    - "bwr"
    - "bwr"
    - "bwr"
    - "bwr"
    #- "bwr"

  scales:
    - [0.0, 1.3]
    - [1.3e4, 1.67e5]
    - [-750.0, 950.0]
    - [-315.0, 315.0]
    #- [0.0,0.05]